"""initial_schema

Revision ID: 17cdc9755460
Revises:
Create Date: 2026-04-16 16:12:20.109649
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17cdc9755460"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("before_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("after_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_table(
        "cf_credentials",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("account_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("token_last_four", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scopes_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(), nullable=True),
        sa.Column("last_verification_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_fingerprint"),
    )
    op.create_index(
        op.f("ix_cf_credentials_is_active"), "cf_credentials", ["is_active"], unique=False
    )
    op.create_table(
        "container_cache",
        sa.Column("container_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("container_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("compose_project", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("compose_service", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("networks_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("exposed_ports_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("labels_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("managed_by_tm", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("container_id"),
    )
    op.create_table(
        "drift_findings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("finding_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expected_value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("actual_value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("details_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("resolution", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drift_findings_scan_id"), "drift_findings", ["scan_id"], unique=False)
    op.create_table(
        "rotation_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("triggered_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("old_token_last_four", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("new_token_last_four", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("downtime_seconds", sa.Float(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("details_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rotation_events_entity_id"), "rotation_events", ["entity_id"], unique=False
    )
    op.create_index(op.f("ix_rotation_events_status"), "rotation_events", ["status"], unique=False)
    op.create_table(
        "zone_cache",
        sa.Column("zone_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zone_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plan_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("refreshed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("zone_id"),
    )
    op.create_index(op.f("ix_zone_cache_account_id"), "zone_cache", ["account_id"], unique=False)
    op.create_index(op.f("ix_zone_cache_zone_name"), "zone_cache", ["zone_name"], unique=False)
    op.create_table(
        "tunnels",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cf_tunnel_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cf_tunnel_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cf_credential_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("token_last_four", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_fetched_at", sa.DateTime(), nullable=False),
        sa.Column("token_deployed_at", sa.DateTime(), nullable=True),
        sa.Column("primary_compose_project", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("primary_compose_service", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cloudflared_container_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cloudflared_image", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rotation_policy", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("next_rotation_due", sa.DateTime(), nullable=True),
        sa.Column("last_rotation_at", sa.DateTime(), nullable=True),
        sa.Column("last_rotation_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cf_credential_id"],
            ["cf_credentials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tunnels_cf_tunnel_id"), "tunnels", ["cf_tunnel_id"], unique=True)
    op.create_index(op.f("ix_tunnels_status"), "tunnels", ["status"], unique=False)
    op.create_table(
        "routes",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tunnel_id", sa.Integer(), nullable=False),
        sa.Column("hostname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path_regex", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("target_compose_project", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_compose_service", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_container_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_scheme", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_port", sa.Integer(), nullable=True),
        sa.Column("target_unix_socket_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_path_prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("no_tls_verify", sa.Boolean(), nullable=False),
        sa.Column("http_host_header", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("origin_server_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("connect_timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("tcp_keep_alive_seconds", sa.Integer(), nullable=True),
        sa.Column("http2_origin", sa.Boolean(), nullable=False),
        sa.Column("zone_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zone_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cf_dns_record_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dns_proxied", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status_detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_healthy_at", sa.DateTime(), nullable=True),
        sa.Column("last_error_at", sa.DateTime(), nullable=True),
        sa.Column("last_error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tunnel_id"],
            ["tunnels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routes_hostname"), "routes", ["hostname"], unique=False)
    op.create_index(op.f("ix_routes_status"), "routes", ["status"], unique=False)
    op.create_index(op.f("ix_routes_tunnel_id"), "routes", ["tunnel_id"], unique=False)
    op.create_table(
        "dns_backups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zone_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hostname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("record_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("record_content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("record_ttl", sa.Integer(), nullable=True),
        sa.Column("record_proxied", sa.Boolean(), nullable=True),
        sa.Column("record_comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("backed_up_at", sa.DateTime(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("related_route_id", sa.Integer(), nullable=True),
        sa.Column("restored_at", sa.DateTime(), nullable=True),
        sa.Column("retention_until", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["related_route_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dns_backups_hostname"), "dns_backups", ["hostname"], unique=False)
    op.create_table(
        "dns_operations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("operation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zone_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cf_record_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hostname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("record_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("old_content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("new_content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("old_proxied", sa.Boolean(), nullable=True),
        sa.Column("new_proxied", sa.Boolean(), nullable=True),
        sa.Column("triggered_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dns_operations_hostname"), "dns_operations", ["hostname"], unique=False
    )
    op.create_table(
        "dns_conflicts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hostname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zone_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("conflict_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("existing_record_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expected_state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("resolution", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resolved_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("dns_backup_id", sa.Integer(), nullable=True),
        sa.Column("route_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dns_backup_id"],
            ["dns_backups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dns_conflicts")
    op.drop_index(op.f("ix_dns_operations_hostname"), table_name="dns_operations")
    op.drop_table("dns_operations")
    op.drop_index(op.f("ix_dns_backups_hostname"), table_name="dns_backups")
    op.drop_table("dns_backups")
    op.drop_index(op.f("ix_routes_tunnel_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_status"), table_name="routes")
    op.drop_index(op.f("ix_routes_hostname"), table_name="routes")
    op.drop_table("routes")
    op.drop_index(op.f("ix_tunnels_status"), table_name="tunnels")
    op.drop_index(op.f("ix_tunnels_cf_tunnel_id"), table_name="tunnels")
    op.drop_table("tunnels")
    op.drop_index(op.f("ix_zone_cache_zone_name"), table_name="zone_cache")
    op.drop_index(op.f("ix_zone_cache_account_id"), table_name="zone_cache")
    op.drop_table("zone_cache")
    op.drop_index(op.f("ix_rotation_events_status"), table_name="rotation_events")
    op.drop_index(op.f("ix_rotation_events_entity_id"), table_name="rotation_events")
    op.drop_table("rotation_events")
    op.drop_index(op.f("ix_drift_findings_scan_id"), table_name="drift_findings")
    op.drop_table("drift_findings")
    op.drop_table("container_cache")
    op.drop_index(op.f("ix_cf_credentials_is_active"), table_name="cf_credentials")
    op.drop_table("cf_credentials")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
